version: "3.3"
services:
  slate:
    command: serve #build # serve
    image: slatedocs/slate
    container_name: slate
    volumes:
      - ./source:/srv/slate/source
      - ./build:/srv/slate/build
    ports:
      - "4567:4567"
    networks:
      - private_docker_network

networks:
  private_docker_network:
    external: true